### ISSUE TITLE
Features Backlog

### ISSUE THREAD

**Issue by williamsmichael** [jasonleonhard/gyfted#13]
- Mobile privacy login
- Frequency (i.e. one-time, weekly, monthly)
- Range of times to pick-up or schedule a meet-time to exchange item
- Locate Me - Find my Location - one-click
- Identify geo coordinates - address verification
- Expiration Date  - calendar picker
- Track the stages of a ticket (time stamps) - statistical
- Mark a ticket as "high priority" and auto-move the ticket to the top of the list

**Comment by jasonleonhard** [comment]
Already was a issue created for this. See: https://github.com/jasonleonhard/gyfted/issues/8 and repost there please.
